name: test

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14.0-beta.3'

      - name: Install SDL libs for pygame‑ce
        run: |
          sudo apt update
          sudo apt install -y \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libfreetype6-dev \
            libjpeg-dev \
            libpng-dev \
            libportmidi-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-mock

      - name: Run tests
        run: pytest --cov --cov-branch --cov-report xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yx-z/nextrpg
